---
name: DBIx-DBO
version: 0.20
author:
  - 'Vernon Lyon <vlyon@cpan.org>'
abstract: 'An OO interface to SQL queries and results.  Easily constructs SQL queries, and simplifies processing of the returned data.'
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-DBO
  license: http://dev.perl.org/licenses/
  repository: https://vlyon.svn.beanstalkapp.com/src/dbo
build_requires:
  File::Temp: 0
  Module::Build: 0.30
  Test::More: 0.62
requires:
  DBI: 1.50
  perl: 5.008001
recommends:
  DBD::Oracle: 1.13
  DBD::Pg: 2
  DBD::SQLite: 1.30
  DBD::mysql: 4.004
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
provides:
  DBIx::DBO:
    file: lib/DBIx/DBO.pm
    version: 0.20
  DBIx::DBO::Query:
    file: lib/DBIx/DBO/Query.pm
  DBIx::DBO::Row:
    file: lib/DBIx/DBO/Row.pm
  DBIx::DBO::Table:
    file: lib/DBIx/DBO/Table.pm
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
