---
name: DBIx-DBO
version: 0.04_02
author:
  - 'Vernon Lyon <vlyon@cpan.org>'
abstract: 'An OO interface to SQL queries and results.  Easily constructs SQL queries, and simplifies processing of the returned data.'
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-DBO
  license: http://dev.perl.org/licenses/
  repository: http://vlyon.svn.beanstalkapp.com/src/dbo
requires:
  DBI: 1.5
  MRO::Compat: 0
  perl: 5.008001
build_requires:
  File::Temp: 0
  Test::More: 0.62
provides:
  DBIx::DBO:
    file: lib/DBIx/DBO.pm
    version: 0.04_02
  DBIx::DBO::Query:
    file: lib/DBIx/DBO/Query.pm
  DBIx::DBO::Row:
    file: lib/DBIx/DBO/Row.pm
  DBIx::DBO::Table:
    file: lib/DBIx/DBO/Table.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
