---
name: DBIx-DBO
version: 0.03
author:
  - 'Vernon Lyon <vlyon@cpan.org>'
abstract: 'An OO interface to SQL queries and results.  Easily constructs SQL queries, and simplifies processing of the returned data.'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.5
  perl: 5.008
build_requires:
  File::Temp: 0
  Test::More: 0.62
recommends:
  MRO::Compat: 0
provides:
  DBIx::DBO:
    file: lib/DBIx/DBO.pm
    version: 0.03
  DBIx::DBO::Query:
    file: lib/DBIx/DBO/Query.pm
  DBIx::DBO::Row:
    file: lib/DBIx/DBO/Row.pm
  DBIx::DBO::Table:
    file: lib/DBIx/DBO/Table.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
repository: http://vlyon.svn.beanstalkapp.com/src/dbo
bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-DBO
