---
name: DBIx-DBO
version: 0.01
author:
  - 'Vernon Lyon <vlyon@cpan.org>'
abstract: An OO interface to SQL queries and results.
license: perl
requires:
  DBI: 1.53
  perl: 5.01
build_requires:
  File::Temp: 0
  Test::More: 0.72
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
repository: http://vlyon.svn.beanstalkapp.com/src/dbo
bugtracker: "http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-DBO"
provides:
  DBIx::DBO:
    file: lib/DBIx/DBO.pm
    version: 0.01
  DBIx::DBO::Common:
    file: lib/DBIx/DBO/Common.pm
  DBIx::DBO::DBD::DBM::Handle:
    file: lib/DBIx/DBO/DBD/DBM.pm
  DBIx::DBO::DBD::Pg::Handle:
    file: lib/DBIx/DBO/DBD/Pg.pm
  DBIx::DBO::DBD::SQLite::Handle:
    file: lib/DBIx/DBO/DBD/SQLite.pm
  DBIx::DBO::DBD::SQLite::Query:
    file: lib/DBIx/DBO/DBD/SQLite.pm
  DBIx::DBO::DBD::mysql::Common:
    file: lib/DBIx/DBO/DBD/mysql.pm
  DBIx::DBO::DBD::mysql::Handle:
    file: lib/DBIx/DBO/DBD/mysql.pm
  DBIx::DBO::DBD::mysql::Query:
    file: lib/DBIx/DBO/DBD/mysql.pm
  DBIx::DBO::Query:
    file: lib/DBIx/DBO/Query.pm
  DBIx::DBO::Row:
    file: lib/DBIx/DBO/Row.pm
  DBIx::DBO::Table:
    file: lib/DBIx/DBO/Table.pm
resources:
  license: http://dev.perl.org/licenses/
